### PR TITLE
Fix for #33

### PR DESCRIPTION
**Pull request by BiryukovVA**

### CODE REVIEW

**Comment by robmoffat** [comment]
HI thanks for your submission.

I released 4.55.10 yesterday - can you say whether this fixes #33 for you?

**Comment by BiryukovVA** [comment]
Hi @robmoffat,
On 4.55.6 fails sometimes.
Cannot find 4.55.10 at DB Artifactory

**Comment by robmoffat** [comment]
> Cannot find 4.55.10 at DB Artifactory

I was using it there on Friday

**Comment by BiryukovVA** [comment]
@robmoffat, 4.55.10 still have flaky failures.

**Comment by robmoffat** [comment]
@BiryukovVA confirmed that existing fix worked for him

**Pull request closed without merging**
